name: Push Creation Tracker
on:
  push:
    branches:
      - "master"
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git Push Details
      run: |
          echo "pus creator: ${{ toJson(github) }}"
 
