name: Push Creation Tracker
on:
  push:
    branches:
      - "master"
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git Push Details
      run: |
          echo "pus creator: ${{ GITHUB_ACTOR }}"
          echo "push title: ${{ GITHUB_JOB }}"
          echo "Issue number: ${{ GITHUB_RUN_ID }}"
          echo "Issue url: ${{ GITHUB_WORKFLOW }}"
          echo "Issue body: ${{ github }}"
          echo "Assigned labels: " ${{ join(github.event.push.labels.*.name) }}
          echo "Assignees: " ${{ join(github.event.push.assignees.*.login) }}
 
