name: other yml
on:
  push:
    branches:
      - "master"    
jobs:
  aprobado:
    runs-on: ubuntu-latest
    steps:
    - name: yml module
      run: |
          echo "Hola soy ${{ github.actor }}"
          exit 1
  fallo:
    runs-on: ubuntu-latest
    steps:
    - name: yml module
      run: |
          echo "Este es un fallo"
          
  comparacion:
    runs-on: ubuntu-latest
    needs: [aprobado, fallo]
    steps:
    - name: Metodo success
      if: success()
      run: |
          echo "Metodo succes"
    - name: Metodo failure
      if: failure()
      run: |
          echo "Metodo failure"
    - name: Metodo allwais
      if: always()
      run: |
          echo "Metodo Alwais"          
