name: other yml
on:
  push:
    branches:
      - "master1"    
jobs:
  aprobado:
    runs-on: ubuntu-latest
    steps:
    - name: yml module
      run: |
          echo "Hola soy ${{ github.actor }}"
          exit 1
      #continue-on-error: true #una especie de try catch, cuando falla aun hace que sea verde el job
    - name: fallo yml module
      if: failure()
      run: |
          echo "Metodo failure"
      
  fallo:
    runs-on: ubuntu-latest
    steps:
    - name: yml module
      run: |
          echo "Este es un fallo"
          
  comparacion:
    runs-on: ubuntu-latest
    needs: [aprobado, fallo]
    steps:
    - name: Metodo success
      if: success()
      run: |
          echo "Metodo succes"
    - name: Metodo failure
      if: failure()
      run: |
          echo "Metodo failure"
    - name: Metodo allwais
      if: always()
      run: |
          echo "Metodo Alwais"     
          
  algo_fallo:
    runs-on: ubuntu-latest
    needs: [aprobado]
    if: failure()
    steps:
    - name: Metodo failure 2
      run: |
          echo "Metodo failure 2" 
     
  
