name: Push Creation Tracker
on:
  push:
    branches:
      - "master"
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git Push Details
      run: |
          echo "pus creator: ${{ github.actor}}"
          echo "pus commit: ${{ github.event.commits[0].message }}"
      id: my_output

    - name: Print my_output
      id: my_variable
      run: |
          echo "::set-output name=test::$(curl --user ${{secrets.SONAR_TOKEN}} https://sonarcloud.io/api/qualitygates/project_status?projectKey='lgmk-nodejs-backend-starter' -o response.json)"
          cd ..
          ls -ltr
          pwd
          echo "::set-output name=otro::$(cat ./response.json)"
          echo "::set-output name=otro2::$(cat ./response.json | jq .projectStatus.status )"
          
    - name: Set selected color
      run: echo 'Verde'
      id: random-color-generator
    - name: Get color
      run: |
           echo "My_Variables1 ${{ steps.my_variable.outputs.test }}"
           echo "My_Variables2 ${{ steps.my_variable.outputs.otro }}"
           echo "My_Variables3 ${{ toJson(steps.my_variable.outputs.otro).projectStatus.status }}"
           echo "My_Variables2 ${{ steps.my_variable.outputs.otro2 }}"
    - uses: ./.github/workflows/other.yml


         
          
