name: Template hello world
on:
  push:
    branches:
      - "master"    
jobs:
  Copy_files:
    runs-on: ubuntu-latest
    steps:
    - name: Copy
      run: |
          ls -ltr
          echo "Hola soy ${{ github.actor }}" | tee copiar_archivos.txt
          ls -ltr
          
  Sonar_Cloud:
    runs-on: ubuntu-latest
    needs: [Copy_files]
    steps:
    - name: analyses
      run: |
          echo "Sonar cloud ls -ltr"
          ls -ltr
      
  Test_JEST:
    runs-on: ubuntu-latest
    needs: [Sonar_Cloud]
    steps:
    - uses: actions/checkout@v3
    - name: run test
      run: |
          echo "Run test"
          ls -ltr
          
  Deploy_servelles:
    runs-on: ubuntu-latest
    needs: [Test_JEST]
    steps:
    - name: Deploy
      run: |
          echo "Metodo deploy"
          exit 1

  Notification:
    runs-on: ubuntu-latest
    needs: [Sonar_Cloud, Test_JEST ,Deploy_servelles]
    if: always()
    steps:
    - name: Send notification
      run: |
          echo "Status SonarCloud ${{needs.Sonar_Cloud.result}}"
          echo "Status Test_JEST ${{needs.Test_JEST.result}}"
          echo "Status Deploy_servelles ${{needs.Deploy_servelles.result}}"
     
  
