name: Template hello world
on:
  push:
    branches:
      - "master"    
jobs:
  Copy_files:
    runs-on: ubuntu-latest
    steps:
    - name: Copy
      run: |
          ls -ltr
          echo "Hola soy ${{ github.actor }}" mi rama es ${GITHUB_REF##*/} | tee copiar_archivos.txt
          ls -ltr
    - name: Upload file 
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_JOHAN }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_JOHAN }}
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
          
  Sonar_Cloud:
    runs-on: ubuntu-latest
    needs: [Copy_files]
    steps:
    - name: analyses
      run: |
          echo "Sonar cloud ls -ltr"
          ls -ltr
      
  Test_JEST:
    runs-on: ubuntu-latest
    needs: [Sonar_Cloud]
    steps:
    - uses: actions/checkout@v3
    - name: run test
      run: |
          echo "Run test"
          ls -ltr
          
  Deploy_servelles:
    runs-on: ubuntu-latest
    needs: [Test_JEST]
    steps:
    - name: Deploy
      run: |
          echo "Metodo deploy"
  #        exit 1

  Notification:
    runs-on: ubuntu-latest
    needs: [Sonar_Cloud, Test_JEST ,Deploy_servelles]
    if: always()
    steps:
    - name: Send notification
      run: |
          echo "Status SonarCloud ${{needs.Sonar_Cloud.result}}"
          echo "Status Test_JEST ${{needs.Test_JEST.result}}"
          echo "Status Deploy_servelles ${{needs.Deploy_servelles.result}}"
          
  Notification_without:
    runs-on: ubuntu-latest
    needs: [Sonar_Cloud, Test_JEST ,Deploy_servelles]
    steps:
    - name: Send notification
      run: |
          echo "Status SonarCloud ${{needs.Sonar_Cloud.result}}"
          echo "Status Test_JEST ${{needs.Test_JEST.result}}"
          echo "Status Deploy_servelles ${{needs.Deploy_servelles.result}}"
     
  
