name: Template hello world
on:
  push:
    branches:
      - "master"    
jobs:
  Copy_files:
    runs-on: ubuntu-latest
    steps:
    - name: Copy
      run: |
          ls -ltr
          echo "Hola soy ${{ github.actor }}" | tee copiar_archivos.txt
          ls -ltr
          
  Sonar_Cloud:
    runs-on: ubuntu-latest
    needs: [Copy_files]
    steps:
    - name: analyses
      if: failure()
      run: |
          echo "Sonar cloud ls -ltr"
          ls -ltr
      
  Test_JEST:
    runs-on: ubuntu-latest
    needs: [Sonar_Cloud]
    steps:
    - name: run test
      run: |
          echo "Run test"
          
  Deploy_servelles:
    runs-on: ubuntu-latest
    needs: [Test_JEST]
    steps:
    - name: Deploy
      run: |
          echo "Metodo deploy"

  Notification:
    runs-on: ubuntu-latest
    steps:
    - name: Metodo success
      run: |
          echo "Metodo succes"
     
  
